print('Welcome to BullFish. After recording your zebrafish videos, this program will analyze their locomotion.')
print('BullFish consists of 3 programs:')
print('- [v]ideosetup: The user will select the video segment and swimming area for tracking and analysis.')
print('                The selections will be saved as a csv file.')
print('                This program will run through each video in the folder and repeat the selection process.')
print('                For each video, the user can also state the angle for video rotation and area for')
print('                cropping to facilitate the tracking.')
print('- [t]racker: After videosetup, this program will automatically track the zebrafish and generate the')
print('             representative coordinates of the zebrafish in each frame for each video.')
print('             This can only be performed after the selections in videosetup have been saved.')
print('- [a]nalysis: After the representative coordinates have been generated by tracker, this program will')
print('              characterize individual episodes of movement and obtain the macro- and micro-parameters.')

print('Enter 1 letter from (v,t,a) to run the program, others to exit:')
program = input()
if program == 'v':
    print('Running videosetup...')
    import BullFish_videosetup
    print('videosetup finished.')
elif program == 't':
    print('Running tracker...')
    import BullFish_tracker
    print('tracker finished.')
elif program == 'a':
    print('Running analysis...')
    import BullFish_analysis
    print('analysis finished.')
